Repository BuiltWithAnalog/builtwithanalog, pull requests merged in 2024-07, with the labels that each got.

#40 styling update and one more project
  dist/.nitro/dev/index.mjs
  dist/.nitro/dev/index.mjs.map
  dist/.nitro/nitro.json
  src/app/pages/(home).page.ts
  src/server/routes/projects.get.ts
  src/styles.scss
Labels: ✨ feature, 🎨 styling, ☯️ theming

#41 images
  public/images/projects/angular-download-tracker.jpg
  public/images/projects/pdfun.jpg
Labels: 🖼️ images & icons

#43 projects from analog discord
  dist/.nitro/dev/index.mjs
  dist/.nitro/dev/index.mjs.map
  dist/.nitro/nitro.json
  public/images/projects/analog-material-anguhashblog.jpg
  public/images/projects/hapax-legomenon.jpg
  public/images/projects/jaybell.jpg
  public/images/projects/monorepox.jpg
  public/images/projects/open-plumbing.jpg
  public/images/projects/tuzuper.jpg
  src/server/routes/projects.get.ts
Labels: ✨ feature, ✅ approved

#44 image path
  dist/.nitro/dev/index.mjs
  dist/.nitro/dev/index.mjs.map
  dist/.nitro/nitro.json
  src/server/routes/projects.get.ts
Labels: 🐛 bug

#45 default value for analog version
  dist/.nitro/dev/index.mjs
  dist/.nitro/dev/index.mjs.map
  dist/.nitro/nitro.json
  src/server/routes/projects.get.ts
Labels: 🐛 bug

#46 about update
  src/app/pages/about.page.ts
  src/app/pages/fqa.page.ts
Labels: ✨ feature

#47 about better
  src/app/pages/about.page.ts
Labels: ✨ feature

#48 fix(home): p-card missing class
  src/app/pages/(home).page.ts
Labels: 🐛 bug, 🎨 styling

#50 feat(sitewide): new default og:image
  index.html
  public/images/projects/builtwithanalog.jpg
Labels: ✨ feature, 🖼️ images & icons

#51 fix(sitewide): default og:image path
  index.html
Labels: ✨ feature, 🖼️ images & icons

#53 feat(pages): responsiveness and chevrondownicon
  dist/.nitro/nitro.json
  src/app/pages/(home).page.ts
  src/app/pages/about.page.ts
  src/app/pages/fqa.page.ts
  src/styles.scss
Labels: ✨ feature, 🎨 styling, 📱responsiveness

#57 feat(ui lib, project): adding Tailwind CSS and a project
  .github/ISSUE_TEMPLATE/project_submission.yml
  .github/PULL_REQUEST_TEMPLATE.md
  dist/.nitro/dev/index.mjs
  dist/.nitro/dev/index.mjs.map
  dist/.nitro/nitro.json
  public/icons/tailwind.svg
  public/images/projects/ngrome.jpg
  src/app/pages/(home).page.ts
  src/server/routes/projects.get.ts
Labels: ✨ feature, ✅ approved, 🎨 styling, 🖼️ images & icons

#63 Feature: Sync filter and URL parameters
  src/app/components/filter.component.ts
  src/app/pages/(home).page.ts
Labels: ✨ feature, 🚦signals

#64 fix(project): project url corrected
  dist/.nitro/dev/index.mjs
  dist/.nitro/dev/index.mjs.map
  dist/.nitro/nitro.json
  src/server/routes/projects.get.ts
Labels: 🐛 bug

#66 angular/build netlify
  package-lock.json
  package.json
Labels: dependencies
